import { Category, Restaurant } from "./interfaces";

export const categories: Category[] = [
  { name: "American", icon: require("../../assets/images/american-icon.png") },
  { name: "Asian", icon: require("../../assets/images/asian-icon.png") },
  {
    name: "Breakfast",
    icon: require("../../assets/images/breakfast-icon.png"),
  },
  { name: "Italian", icon: require("../../assets/images/italian-icon.png") },
  {
    name: "Mediterranean",
    icon: require("../../assets/images/mediterranean-icon.png"),
  },
  { name: "Desserts", icon: require("../../assets/images/desserts-icon.png") },
  { name: "Seafood", icon: require("../../assets/images/seafood-icon.png") },
  { name: "Vegan", icon: require("../../assets/images/vegan-icon.png") },
];

export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "Bubby’s Diner",
    location: "Terminal C - near gate 71",
    rating: 4.5,
    hours: "10:00 am - 8:30 pm",
    priceRange: "$10-20",
    deliveryTime: "Delivers in 30 - 40 mins",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8ae8p5fO5SDVCFj-xEWTJaECdaCkzSx0jsA&s",
    favorite: false,
    available: false,
  },
  {
    id: "2",
    name: "Calista Tavern",
    location: "Terminal C - near gate 71",
    rating: 4.7,
    hours: "10:00 am - 8:30 pm",
    priceRange: "$10-20",
    deliveryTime: "Delivers in 30 - 40 mins",
    image:
      "https://b.zmtcdn.com/data/pictures/1/20509371/483f0c9ee3e4f27111cb208426cc3f4d_featured_v2.jpg",
    favorite: true,
    available: true,
  },
  {
    id: "3",
    name: "Bubby’s Diner",
    location: "Terminal C - near gate 71",
    rating: 4.2,
    hours: "10:00 am - 8:30 pm",
    priceRange: "$10-20",
    deliveryTime: "Unavailable",
    image:
      "https://content.jdmagicbox.com/comp/def_content_category/the-burger-company/243004959-3017123925236597-1302513494595748963-n-the-burger-company-9-zrd8g-250.jpg",
    favorite: false,
    available: false,
  },
  {
    id: "4",
    name: "Sushi Delight",
    location: "Terminal B - near gate 50",
    rating: 4.8,
    hours: "9:00 am - 9:00 pm",
    priceRange: "$15-30",
    deliveryTime: "Delivers in 20 - 30 mins",
    image: "https://images.unsplash.com/photo-1608478641099-7fc1f5cd4c8b",
    favorite: true,
    available: true,
  },
  {
    id: "5",
    name: "Pasta Paradise",
    location: "Terminal A - near gate 12",
    rating: 4.3,
    hours: "11:00 am - 10:00 pm",
    priceRange: "$12-25",
    deliveryTime: "Delivers in 25 - 35 mins",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
    favorite: false,
    available: true,
  },
  {
    id: "6",
    name: "Grill Master",
    location: "Terminal D - near gate 32",
    rating: 4.6,
    hours: "12:00 pm - 11:00 pm",
    priceRange: "$20-40",
    deliveryTime: "Delivers in 40 - 50 mins",
    image: "https://images.unsplash.com/photo-1604152135912-04a022b6a537",
    favorite: false,
    available: true,
  },
  {
    id: "7",
    name: "Healthy Bites",
    location: "Terminal C - near gate 20",
    rating: 4.9,
    hours: "7:00 am - 8:00 pm",
    priceRange: "$8-15",
    deliveryTime: "Delivers in 15 - 20 mins",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    favorite: true,
    available: true,
  },
  {
    id: "8",
    name: "Taco Fiesta",
    location: "Terminal B - near gate 44",
    rating: 4.4,
    hours: "11:30 am - 9:30 pm",
    priceRange: "$10-18",
    deliveryTime: "Delivers in 35 - 45 mins",
    image: "https://images.unsplash.com/photo-1551504734-20c6c1464957",
    favorite: false,
    available: true,
  },
  {
    id: "9",
    name: "Pizza Haven",
    location: "Terminal A - near gate 7",
    rating: 4.7,
    hours: "10:30 am - 10:30 pm",
    priceRange: "$12-22",
    deliveryTime: "Delivers in 30 - 40 mins",
    image: "https://images.unsplash.com/photo-1547592180-8731b8c532a7",
    favorite: true,
    available: false,
  },
  {
    id: "10",
    name: "The Coffee Spot",
    location: "Terminal D - near gate 15",
    rating: 4.5,
    hours: "6:00 am - 7:00 pm",
    priceRange: "$5-12",
    deliveryTime: "Delivers in 10 - 15 mins",
    image: "https://images.unsplash.com/photo-1523942839745-7848e28cb902",
    favorite: false,
    available: true,
  },
];
